// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';
import 'package:meta/meta.dart';

class Id3TagsPlatform extends FlutterRustBridgeBase<Id3TagsWire>
    with FlutterRustBridgeSetupMixin {
  Id3TagsPlatform(FutureOr<WasmModule> dylib) : super(Id3TagsWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;
// Section: api2wire

  @protected
  String api2wire_String(String raw) {
    return raw;
  }

  @protected
  int /* *i32 */ api2wire_box_autoadd_i32(int raw) {
    return inner.new_box_autoadd_i32_0(api2wire_i32(raw));
  }

  @protected
  List<dynamic> api2wire_box_autoadd_tag(Tag raw) {
    return api2wire_tag(raw);
  }

  @protected
  int /* *u32 */ api2wire_box_autoadd_u32(int raw) {
    return inner.new_box_autoadd_u32_0(api2wire_u32(raw));
  }

  @protected
  String? api2wire_opt_String(String? raw) {
    return raw == null ? null : api2wire_String(raw);
  }

  @protected
  int /* *i32 */ ? api2wire_opt_box_autoadd_i32(int? raw) {
    return raw == null ? 0 : api2wire_box_autoadd_i32(raw);
  }

  @protected
  int /* *u32 */ ? api2wire_opt_box_autoadd_u32(int? raw) {
    return raw == null ? 0 : api2wire_box_autoadd_u32(raw);
  }

  @protected
  Uint8List? api2wire_opt_uint_8_list(Uint8List? raw) {
    return raw == null ? null : api2wire_uint_8_list(raw);
  }

  @protected
  List<dynamic> api2wire_tag(Tag raw) {
    return [
      api2wire_opt_String(raw.title),
      api2wire_opt_String(raw.artist),
      api2wire_opt_String(raw.album),
      api2wire_opt_box_autoadd_i32(raw.year),
      api2wire_opt_String(raw.genre),
      api2wire_opt_box_autoadd_u32(raw.duration),
      api2wire_opt_uint_8_list(raw.picture)
    ];
  }

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }
}

// Section: WASM wire module

@JS('wasm_bindgen')
external Id3TagsWasmModule get wasmModule;

@JS()
@anonymous
class Id3TagsWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external Id3TagsWasmModule bind(dynamic thisArg, String moduleName);
  external void wire_read(NativePortType port_, String path);

  external void wire_write(
      NativePortType port_, String path, List<dynamic> data);

  external int /* *mut i32 */ new_box_autoadd_i32_0(int value);

  external int /* *mut u32 */ new_box_autoadd_u32_0(int value);
}

// Section: WASM wire connector

class Id3TagsWire extends FlutterRustBridgeWasmWireBase<Id3TagsWasmModule> {
  Id3TagsWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<Id3TagsWasmModule>(module));

  void wire_read(NativePortType port_, String path) =>
      wasmModule.wire_read(port_, path);

  void wire_write(NativePortType port_, String path, List<dynamic> data) =>
      wasmModule.wire_write(port_, path, data);

  int /* *mut i32 */ new_box_autoadd_i32_0(int value) =>
      wasmModule.new_box_autoadd_i32_0(value);

  int /* *mut u32 */ new_box_autoadd_u32_0(int value) =>
      wasmModule.new_box_autoadd_u32_0(value);
}
