// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.65.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

abstract class Audiotags {
  Future<Tag> read({required String path, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReadConstMeta;

  Future<void> write({required String path, required Tag data, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kWriteConstMeta;
}

/// Represents the metadata of the file.
class Tag {
  /// The title of the song.
  final String? title;

  /// The artist of the song.
  final String? artist;

  /// The album the song is from.
  final String? album;

  /// The year that this song was made.
  final int? year;

  /// The genre of the song.
  final String? genre;

  /// The duration of the song. Setting this field
  /// when writing will do nothing.
  final int? duration;

  /// The front cover of the song in bytes.
  final Uint8List? picture;
  Tag({
    this.title,
    this.artist,
    this.album,
    this.year,
    this.genre,
    this.duration,
    this.picture,
  });
}
