[package]
name = "audiotags"
version = "1.3.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "=1.82.1"
lofty = "0.16.0"

[dev-dependencies]
anyhow = "1.0.68"

[profile.release]
lto = true
